# ### Get all agents
GET http://127.0.0.1:8000/agents
Accept: application/json

# ### Get a specific agent by ID
# GET http://127.0.0.1:8000/agents/1
# Accept: application/json

### Create a new agent
POST http://127.0.0.1:8000/agents
Content-Type: application/json
Accept: application/json

{
    "codename": "007",
    "specialty": "Espionage"
}

### Update an agent
PUT http://127.0.0.1:8000/agents/1
Content-Type: application/json
Accept: application/json

{
    "codename": "007",
    "specialty": "Counterintelligence"
}